services:
  web: 
    build: .
    command: ["python3", "main.py"]
    env_file:
      - .env
    ports: 
      - "8000:8000"
    depends_on:
      - db 
      - redis 
    volumes:
      - ./app:/app 

  resume_worker:
    build: .
    command: ["python3", "resume_evaluation_worker.py"]
    depends_on: 
     - redis

  related_jobs_worker:
    build: .
    command: python3 related_jobs_worker.py 
    depends_on: 
     - redis

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
  
