version: "3.8"
services:
  app:
    build: . 
    command: ["sh", "-c", "sleep 10 && python3 main.py"]
    ports:
      - '8000:8000'
    depends_on:
      - db 
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    volumes:
      - ./app:/app 

  resume_worker:
    build: .
    command: ["python3", "resume_evaluation_worker.py"]
    depends_on: 
     - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    volumes:
      - ./app:/app
 
  related_jobs_worker:
    build: .
    command: ["python3", "related_jobs_worker.py"] 
    depends_on: 
     - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    volumes:
      - ./app:/app

  redis:
    image: redis:6
    restart: always
    ports:
      - '6380:6379'

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: